import type { ModeConfig } from '../types';

export const MODES: ModeConfig[] = [
  {
    id: 'general',
    label: 'General Chat',
    labelNe: 'सामान्य कुराकानी',
    description: 'Natural conversation, questions, and general assistance',
    descriptionNe: 'सामान्य कुराकानी, प्रश्न र सहायता',
    icon: '💬',
    color: 'from-blue-500 to-indigo-600',
    bgGradient: 'from-blue-50 to-indigo-50',
    placeholder: 'Ask me anything — in Nepali or English...',
    placeholderNe: 'केही पनि सोध्नुहोस् — नेपाली वा अंग्रेजीमा...',
    placeholderShort: 'Type your message...',
    placeholderShortNe: 'आफ्नो सन्देश लेख्नुहोस्...',
  },
  {
    id: 'document',
    label: 'Document Analysis',
    labelNe: 'कागजात विश्लेषण',
    description: 'Analyze government forms, legal papers & official documents',
    descriptionNe: 'सरकारी फारम, कानूनी कागजात र आधिकारिक कागजात विश्लेषण गर्नुहोस्',
    icon: '📄',
    color: 'from-emerald-500 to-teal-600',
    bgGradient: 'from-emerald-50 to-teal-50',
    placeholder: 'Paste or describe your document content here...',
    placeholderNe: 'आफ्नो कागजातको सामग्री यहाँ टाँस्नुहोस् वा वर्णन गर्नुहोस्...',
    placeholderShort: 'Paste document text...',
    placeholderShortNe: 'कागजातको पाठ टाँस्नुहोस्...',
  },
  {
    id: 'scam',
    label: 'Scam Detector',
    labelNe: 'ठगी पहिचान',
    description: 'Detect fraud in SMS, emails, links & suspicious messages',
    descriptionNe: 'SMS, इमेल, लिंक र संदिग्ध सन्देशमा ठगी पत्ता लगाउनुहोस्',
    icon: '🛡️',
    color: 'from-red-500 to-rose-600',
    bgGradient: 'from-red-50 to-rose-50',
    placeholder: 'Paste suspicious message, email, or URL here...',
    placeholderNe: 'संदिग्ध सन्देश, इमेल वा URL यहाँ टाँस्नुहोस्...',
    placeholderShort: 'Paste suspicious text...',
    placeholderShortNe: 'संदिग्ध पाठ टाँस्नुहोस्...',
  },
  {
    id: 'legal',
    label: 'Legal & Civic',
    labelNe: 'कानूनी र नागरिक',
    description: 'Nepal legal guidance, rights & government procedures',
    descriptionNe: 'नेपाल कानूनी मार्गदर्शन, अधिकार र सरकारी प्रक्रिया',
    icon: '⚖️',
    color: 'from-amber-500 to-orange-600',
    bgGradient: 'from-amber-50 to-orange-50',
    placeholder: 'Ask about your legal rights or government procedures...',
    placeholderNe: 'आफ्नो कानूनी अधिकार वा सरकारी प्रक्रियाबारे सोध्नुहोस्...',
    placeholderShort: 'Ask about rights or procedures...',
    placeholderShortNe: 'अधिकार वा प्रक्रियाबारे सोध्नुहोस्...',
  },
];

export const MODE_COLORS = {
  general: {
    primary: '#3b82f6',
    secondary: '#6366f1',
    light: '#eff6ff',
    border: '#bfdbfe',
    text: '#1d4ed8',
    badge: 'bg-blue-100 text-blue-700 border-blue-200',
    button: 'bg-blue-600 hover:bg-blue-700',
    bubble: 'bg-gradient-to-br from-blue-500 to-indigo-600',
  },
  document: {
    primary: '#10b981',
    secondary: '#0d9488',
    light: '#f0fdf4',
    border: '#a7f3d0',
    text: '#065f46',
    badge: 'bg-emerald-100 text-emerald-700 border-emerald-200',
    button: 'bg-emerald-600 hover:bg-emerald-700',
    bubble: 'bg-gradient-to-br from-emerald-500 to-teal-600',
  },
  scam: {
    primary: '#ef4444',
    secondary: '#e11d48',
    light: '#fff1f2',
    border: '#fecdd3',
    text: '#9f1239',
    badge: 'bg-red-100 text-red-700 border-red-200',
    button: 'bg-red-600 hover:bg-red-700',
    bubble: 'bg-gradient-to-br from-red-500 to-rose-600',
  },
  legal: {
    primary: '#f59e0b',
    secondary: '#ea580c',
    light: '#fffbeb',
    border: '#fde68a',
    text: '#92400e',
    badge: 'bg-amber-100 text-amber-700 border-amber-200',
    button: 'bg-amber-600 hover:bg-amber-700',
    bubble: 'bg-gradient-to-br from-amber-500 to-orange-600',
  },
} as const;

export const QUICK_PROMPTS: Record<string, string[]> = {
  general: [
    'नेपालको राजधानी के हो र त्यहाँ के के छ?',
    'What are the major festivals celebrated in Nepal?',
    'नेपालमा मौसम कस्तो हुन्छ?',
    'Tell me about Nepal\'s geography and culture',
  ],
  document: [
    'Analyze this citizenship certificate text...',
    'मेरो जग्गा दर्ता कागजात बुझ्न मद्दत गर्नुस्',
    'Explain what this bank notice means...',
    'मेरो श्रम स्वीकृति पत्र के भन्छ?',
  ],
  scam: [
    'Check if this job offer is real: "Earn NPR 50,000 working from home..."',
    'मलाई यस्तो SMS आयो, के यो ठगी हो?',
    'Is this link safe? bit.ly/win-prize-nepal',
    '"Congratulations! You won NPR 5 lakh lottery" — is this real?',
  ],
  legal: [
    'नागरिकता बनाउने प्रक्रिया के हो?',
    'What are my rights if I am wrongfully terminated from my job?',
    'जग्गा किनबेच गर्दा के गर्नु पर्छ?',
    'How do I file a consumer complaint in Nepal?',
  ],
};
